//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTallPizzaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int idProduto { get; set; }
        public string nome { get; set; }
        public Nullable<decimal> preco { get; set; }
        public string descricao { get; set; }
        public string foto { get; set; }
        public Nullable<int> idTipo { get; set; }
        public Nullable<bool> SUGESTAO { get; set; }
        public Nullable<bool> DESTAQUES { get; set; }
        public Nullable<System.DateTime> DATAMODIFICACAOSUGESTAO { get; set; }
        public Nullable<System.DateTime> DATAMODIFICACAODESTAQUE { get; set; }
    
        public virtual TipoProduto TipoProduto { get; set; }
    }
}
