//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTallPizzaria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBQtallEntities : DbContext
    {
        public DBQtallEntities()
            : base("name=DBQtallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<banner> banner { get; set; }
        public virtual DbSet<Foto> Foto { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<TipoProduto> TipoProduto { get; set; }
    }
}
