//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTallPizzaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sugestao
    {
        public int idSugestao { get; set; }
        public Nullable<int> idTipo { get; set; }
        public Nullable<int> idProduto { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual TipoProduto TipoProduto { get; set; }
    }
}
