//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTallPizzaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public int idBanner { get; set; }
        public string diretorio { get; set; }
    }
}
